    - name: Pull Docker image and run container
      community.docker.docker_container:
        name: my-frontend-app
        image: nodejsapp-backend-img:latest
        state: started
        ports:
          - "4000:8080"
        env:
          APP_ENV: production
        restart_policy: always
