    - name: Git-checkout
      git: repo="https://github.com/Devops2022jk/Ansible-Role-Demo.git" dest="/home/ubuntu/two-tier-app/"

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: latest
        update_cache: yes

    - name: Install Docker Python SDK
      pip:
        name: docker
        state: latest

    - name: Pull Docker image and run container
      community.docker.docker_container:
        name: my-frontend-app
        image: devopsjk2023/phpapp-frontend-img:latest
        state: started
        ports:
          - "3000:80"
        env:
          APP_ENV: production
        restart_policy: always
